version: 0.0
os: linux
files:
  - source: /
    destinatnion: /home/ec2-user/com.ryu.pt.springboot/comryu-springboot-build
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user